language: cpp
compiler:
  - gcc
  - clang
script: make
branches:
  only:
    - master
    - develop
notifications:
  recipients:
    - jan.milik@gmail.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
